#205974876
 
#sendrot

compile: bin
	javac -cp biuoop-1.4.jar:. -d bin src/*/*.java src/*.java

run:
	java -cp biuoop-1.4.jar:bin:resources: Ass7Game

jar:
	jar cvfm ass7game.jar MANIFEST.MF -C bin . -C resources .

bin:
	mkdir bin
